name: Build Check

on:
  push:
    branches: ["main"]
    paths:
      - "main/**"
  pull_request:
    paths:
      - "main/**"

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      # Dockerfileを使って、ランナーの中でDockerイメージをビルド
      - name: Build Docker image
        run: docker build -t etrobo2026_builder .

      # コンテナを起動し、main ディレクトリのビルドを実行する
      - name: Run build in container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/main:/etrobo/spike-rt/sdk/workspace/main \
            etrobo2026_builder \
            bash -c "make img=main -C /etrobo/spike-rt/sdk/workspace"
